### PR TITLE
Feature/378

### PR DESCRIPTION
**Pull request by zsinnema**
# Filter values are not being reset when switching from test score view to suite view causing some confusion
#378 

## Changes
Fix owner filter on score and suite pages
Move owner, timestamp from and timestamp to filters to become global (for score & suite pages)

## Related issues
#378

### CODE REVIEW

**Review by jrmartin — COMMENTED** [review]
I tested this branch locally, the issue with the filters getting reset when switching from Test Scores to Suite Scores view is fixed. 

However, a new issue was introduced:
Step 1: Load scidash with timestamps as part of the URL , e.g.
http://localhost:8000/?timestamp_to=2018-07-30&timestamp_from=2018-06-01&status=c

Step2 : Page gets loaded, and you briefly see the main page populated with Test Scores, but they disappear within a second. Then they appear back a few seconds later. The timestamps in the UI header fields don't reflect the timestamps passed as part of the URL either, you have to click on the 'Reset' button for the timestamps in UI to be updated with the values passed in the URL, and that only updates the first timestamp for the 'From' date.

**Comment by zsinnema** [comment]
I also noticed that not every filter is reset when accessing the system with URL parameters.
@gidili in case of URL parameter do we want to reset all filters and take only the URL parameters? For example the default owner==user filter can then also be skipped. Or do we want the owner to be default set when user is logged in and accessing a page via a direct URL entry?

--
I've implemented it like this:
when the user is logged in then when owner is omitted the default for the owner (the current user) will be added to the URL params. However when you add `&owner=` to the URL params then the filter will search "all"

**Comment by jrmartin** [comment]
@zsinnema That last commit did it, the timestamps in the UI are now the ones taken from the URL.

**Review by ddelpiano — CHANGES_REQUESTED** [review]
changes requested as per bug noticed during testing.

**Review by ddelpiano — APPROVED** [review]

**Pull request merged**
