### PR TITLE
fix: eye icon suites matrix not working correctly

### PR DESCRIPTION
**Pull request by zsinnema**
# Suites view - eye icon in the matrix opened by the test name link or the score link is not working as it should
#405 

## Changes
changed creating new object into singleton usage

### CODE REVIEW

**Comment by gidili** [comment]
@zsinnema can we open this against development instead of master? (we never open PRs against master if not from development)

**Comment by ddelpiano** [comment]
@zsinnema this does not work still for me.
The global eye icon swap the order of the results from ascending to descending, where (@gidili correct me if wrong) that icon should hide and show all the results.

Then the eye icon per record should hide/show the single row.

video attached.

[Jan-15-2020 18-45-10.mp4.zip](https://github.com/MetaCell/geppetto-scidash/files/4066388/Jan-15-2020.18-45-10.mp4.zip)

**Review by ddelpiano — CHANGES_REQUESTED** [review]
copy-paste of the previous message left in the PR.

@zsinnema this does not work still for me.
The global eye icon swap the order of the results from ascending to descending, where (@gidili correct me if wrong) that icon should hide and show all the results.

Then the eye icon per record should hide/show the single row.

**Review by ddelpiano — CHANGES_REQUESTED** [review]
@zsinnema still does not work.

Same behaviour described yesterday, the eye icon in the top-right corner is changing the results order from ascending to descending and viceversa, where this should hide/show all the results instead.

The single row/record eye icon still does not work, when I try to use it I get the below in console.

```
Uncaught ReferenceError: AdapterException is not defined
    at Function.getInstance (ScoreMatrixGriddleAdapter.js:12)
    at hideModel (test-suites.js:58)
    at scidashTestSuites (scidash-test-suites.js:44)
    at combination (combineReducers.js:120)
    at reducer.js:50
    at dispatch (createStore.js:165)
    at redux-logger.js:1
    at middleware.js:25
    at hideRow (TestSuitesContainer.js:92)
    at onClick (partials.js:26)
```

**Comment by zsinnema** [comment]
> @zsinnema still does not work.
> 
> Same behaviour described yesterday, the eye icon in the top-right corner is changing the results order from ascending to descending and viceversa, where this should hide/show all the results instead.
> 
> The single row/record eye icon still does not work, when I try to use it I get the below in console.
> 
> ```
> Uncaught ReferenceError: AdapterException is not defined
>     at Function.getInstance (ScoreMatrixGriddleAdapter.js:12)
>     at hideModel (test-suites.js:58)
>     at scidashTestSuites (scidash-test-suites.js:44)
>     at combination (combineReducers.js:120)
>     at reducer.js:50
>     at dispatch (createStore.js:165)
>     at redux-logger.js:1
>     at middleware.js:25
>     at hideRow (TestSuitesContainer.js:92)
>     at onClick (partials.js:26)
> ```

this is fixed in PR https://github.com/MetaCell/scidash/pull/149 (scidash). The issue was a wrong pull from the geppetto scidash extension in the install-frontend.sh . The Makefile macro didn't pass the command line args to this script.

**Review by ddelpiano — CHANGES_REQUESTED** [review]
Already discussed with @zsinnema (sorry again to be a pain 😂 ), I can see now the matrix working but I spotted an issue when I try to hide all the records.
```
Uncaught TypeError: Cannot read property 'length' of undefined
    at ShowAllHeading (partials.js:29)
    at ReactCompositeComponent.js:306
    at measureLifeCyclePerf (ReactCompositeComponent.js:75)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (ReactCompositeComponent.js:305)
    at ReactCompositeComponentWrapper._constructComponent (ReactCompositeComponent.js:280)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:188)
    at Object.mountComponent (ReactReconciler.js:46)
    at Object.mountComponent (backend.js:32)
    at Object.e.<computed> [as mountComponent] (backend.js:32)
    at ReactDOMComponent.mountChildren (ReactMultiChild.js:238)
```

**Review by ddelpiano — APPROVED** [review]

**Pull request merged**
